# TODO: job-runner is wrong here, I should name it stockfish/stockfish or something. I guess this would ostensibly
# contain multiple CRDs? I'm not sure what the best practice is here.
apiVersion: job-runner.emerald.city/v1alpha1
kind: Stockfish
metadata:
  labels:
    app.kubernetes.io/name: stockfish-operator
    app.kubernetes.io/managed-by: kustomize
  name: stockfish-sample
  namespace: lab
spec:
  position: "position startpos moves d2d4 d7d5 Bc4 Nc6 e4 e6 Nf3 Bb4+ Nc3 Nf6 O-O Bxc3 bxc3 Nxe4"
  depth: 50
  lines: 5
