---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job-runner.emerald.city
  resources:
  - stockfish
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job-runner.emerald.city
  resources:
  - stockfish/finalizers
  verbs:
  - update
- apiGroups:
  - job-runner.emerald.city
  resources:
  - stockfish/status
  verbs:
  - get
  - patch
  - update
